@echo off
cd /d "%~dp0"
echo Starting LumiQuote, please wait...
echo Installing dependencies - this may take a few minutes the first time...
call npm install
echo Launching LumiQuote...
npm start
pause